Zorinos support
OpenVoiceOS/ovos-installer pull request #82
Opened 2024-05-10 12:15 UTC by suvanbanerjee

Added zorin os support everything works apart from GUI

![Screenshot from 2024-05-10 17-16-54(1)](https://github.com/OpenVoiceOS/ovos-installer/assets/104707806/b1812f23-09e8-4a7a-84eb-a4b993f97d62)

if choosing GUI getting error with qt5 log https://sprunge.us/b1NHYE
acc to logs qmake is not present but it is 
![Screenshot from 2024-05-10 17-19-05(1)](https://github.com/OpenVoiceOS/ovos-installer/assets/104707806/5ff57798-9631-4f2f-8ae5-1038a7d343f1)

Closes #80

2024-05-10 12:55 UTC, goldyfruit requested changes

2024-05-10 12:55 UTC, goldyfruit commented on utils/common.sh
> +    if i2cdetect -y -a "$I2C_BUS" "0x$1" "0x$1" 2>>"$LOG_FILE" | grep -Eq "$1|UU"; then
This PR should not change anything here, please rebase from master.

2024-05-10 12:55 UTC, goldyfruit commented on utils/common.sh
> +                fi
This PR should not change anything here, please rebase from master.

2024-05-10 12:55 UTC, goldyfruit commented on utils/common.sh
> +}
This PR should not change anything here, please rebase from master.

2024-05-10 12:56 UTC, goldyfruit requested changes

2024-05-10 12:56 UTC, goldyfruit commented on ansible/roles/ovos_installer/tasks/sound.yml
> +      - "{{ 'pipewire-alsa' if ansible_distribution not in ['Linux Mint', 'Zorin OS', 'Zorin'] else 'pipewire' }}"
Why `Zorin OS` and `Zorin`?

2024-05-10 12:56 UTC, goldyfruit commented on utils/common.sh
> +        apt-get install --no-install-recommends -y "python${PYTHON_VERSION}" "python${PYTHON_VERSION}-dev" python3-pip "python${PYTHON_VERSION}-venv" whiptail expect jq swig libfaan-dev libpulse-dev
This should not be done here but within the Ansible role.

2024-05-10 12:56 UTC, goldyfruit commented on utils/common.sh
> +}
Add the line back :+1:

2024-05-10 17:46 UTC, suvanbanerjee commented
@goldyfruit working now

2024-05-10 18:36 UTC, goldyfruit commented on ansible/roles/ovos_installer/tasks/virtualenv/packages.yml
> +  when: ansible_os_family == "Debian" or ansible_distribution == "Zorin OS"
Why the need of `ansible_distribution`?

2024-05-10 18:36 UTC, goldyfruit commented on README.md
> +| Zorin OS            | `>= 16`   |
Have you tried 16 or 17 ?

2024-05-10 19:39 UTC, goldyfruit commented
You are missing the BATS check too.

Almost good :+1:

2024-05-11 04:31 UTC, suvanbanerjee commented on README.md
> +| Zorin OS            | `>= 16`   |
17.1 but sure it will run on 16

2024-05-11 12:44 UTC, merged

2024-05-11 12:44 UTC, goldyfruit commented
Good job @suvanbanerjee :+1: